---
- name: nano? #name of play
  hosts: linux #your host group in your "/etc/ansible/hosts" file
  pre_tasks:
    - name: update distribution
      tags: always
      package:
        name: "*"
        state: latest
  tasks:
    - name: Install nano, htop, and tmux #name of task
      tags: centos,nano,htop,tmux
      package: #instead of a specific package manager we use "package" since it's generic and works for multiple distros
        name: #Drop the names onto another line and hyphenate when doing multiple packages
          - nano
          - htop
          - tmux
        state: latest


    - name: create jarvis user #Creating a user that runs tasks in the background
      tags: users
      user: 
        name: jarvis
        groups: root


    - name: add ssh key for jarvis
      tags: users
      authorized_key:
        user: jarvis
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDOKSHtEkB4Azn7GybJPpXStE7FwRul1oQ/vvSpc4/Hn ansible"


    - name: add sudoers file for jarvis
      tags: users
      copy:
        src: sudoer_jarvis
        dest: /etc/sudoers.d/jarvis
        owner: root
        group: root
        mode: 0440


    - name: This is a file play #this is is the part that is new for this playbook
      tags: dont_do #placeholder tag so this doesn't run with the other files tags
      copy:
        src: /home/user/test.txt #file to copy
        dest: /home/user/test.txt #where to copy it to
        owner: root
        group: root
        mode: 0644 #sets permissions for the file


    - name: install unzip #this play installs unzip so that the next play will unzip the terraform zip file
      tags: files
      package:
        name: unzip


    - name: install terraform #this play will install packages from a remote source instead of through your package manager
      tags: files
      unarchive: # this module allows us to unzip a compressed file
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes # this notates that the source is in fact remote and not a local file
        mode: 0755
        owner: root
        group: root