---
- name: nano? #name of play
  hosts: linux #your host group in your "/etc/ansible/hosts" file
  pre_tasks:
    - name: update distribution
      tags: always
      package:
        name: "*"
        state: latest
  tasks:
    - name: Install nano, htop, and tmux #name of task
      tags: centos,nano,htop,tmux
      package: #instead of a specific package manager we use "package" since it's generic and works for multiple distros
        name: #Drop the names onto another line and hyphenate when doing multiple packages
          - nano
          - htop
          - tmux
        state: latest